# Generated by Django 5.2.14 on 2026-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('popup', '팝업스토어'), ('exhibition', '전시'), ('festival', '페스티벌/공연'), ('fair', '박람회'), ('other', '기타')], default='popup', max_length=50)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('detail_url', models.URLField(blank=True, max_length=1000)),
                ('hashtags', models.JSONField(default=list)),
                ('source', models.CharField(default='dayforyou', max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='events_even_start_d_7e0d92_idx'), models.Index(fields=['category'], name='events_even_categor_aca11d_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
