# Generated by Django 5.2.14 on 2026-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='audience_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='detail_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='emotion_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='main_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='mood_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='music_genre',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='space_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='vector_summary',
            field=models.TextField(blank=True),
        ),
    ]
