# Generated by Django 5.2.14 on 2026-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_activity_tags_event_audience_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='store_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
