# Generated by Django 5.2.14 on 2026-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commerciality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='exhibition_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='new_audience_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='new_main_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='new_mood_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='new_sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='vector_summary_v2',
            field=models.TextField(blank=True),
        ),
    ]
